### ISSUE TITLE
Compatiblity with TypeDoc 0.22.X

### ISSUE THREAD

**Issue by jonamenk** [mipatterson/typedoc-plugin-pages#64]
TypeDoc introduced breaking changes in 0.22.X

The plugin is therefor incompatible with the following error:

```
Error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/lib/utils/options/declaration' is not defined by "exports" in /workspace/node_modules/typedoc/package.json
at new NodeError (internal/errors.js:322:7)
    at throwExportsNotFound (internal/modules/esm/resolve.js:322:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:545:3)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/workspace/node_modules/typedoc-plugin-pages/dist/plugin/index.js:7:23)
```

**Comment by kamtschatka** [comment]
Is the project still active? Are there plans to make it compatible with typescript 4.5 or is it even possible?

**Comment by crackedpotato007** [comment]
Appears dead

**Comment by tony-scio** [comment]
It's a shame. Was just trying to use it and ran into this.

**Comment by FlorianCassayre** [comment]
It's a shame indeed. I've been using `typedoc-plugin-pages-fork-fork` which is compatible with Typedoc `0.22.0` but has died as well. I wonder if there are alternatives, this is such a crucial feature!

**Edit**: it seems there is! The Typedoc website now points to [@knodes/typedoc-plugin-pages](https://github.com/KnodesCommunity/typedoc-plugins/tree/main/packages/plugin-pages).
